spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  application:
    name: rental-ms-member
  profiles:
    active: default
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8083

logging:
  level:
    org.hibernate.SQL: debug
